version: "3.7"

volumes:
  datadb:

services:
  mysql:
    image: mysql:lts
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: koublis
      MYSQL_USER: celld
      MYSQL_PASSWORD: secret123
    ports:
      - "3306:3306"
    volumes:
      - datadb:/var/lib/mysql