version: "2.2"

volumes:
  datadb:

services:

  mongo:
    image: mongo
    container_name: springboot-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - datadb:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example


  springboot:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: springboot
    restart: always
    ports:
      - '8080:8080'
      - '8000:8000'
    environment:
      ME_CONFIG_MONGODB_SERVER: koublis

