version: "2.2"

volumes:
  datadb:

services:

  db:
    image: mysql:8.0
    container_name: db_mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=koublis
      - MYSQL_USER=koublis
      - MYSQL_PASSWORD=koublis_password
    volumes:
      - datadb:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

  back:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: springboot
    restart: always
    ports:
      - '8080:8080'
      - '8000:8000'

