spring:
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme
  datasource:
    url: jdbc:mysql://localhost:3306/koublis?sslMode=PREFERRED
    username: celld
    password: secret123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0

koublis:
  catalog:
    location: catalog/catalog.json
  security:
    jwtSecret: j6F326G7UuS7wmIJ3Pca9vwV/s0QoIXImMsZMVG96cY=
    jwtExpiration: 24h

logging:
  level:
    com.koublis: debug