spring:
  datasource:
    url: ${MYSQL_URL}/koublis
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

koublis:
  security:
    jwtSecret: ${SECRET_KEY}
    jwtExpiration: 24h