---
apiVersion: v1
kind: Namespace
metadata:
  name: koublis
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5yaXZvYWwubWwiOnsidXNlcm5hbWUiOiJyaXZvYWwiLCJwYXNzd29yZCI6Im5YOHMzaXlkNHpuNXdzUnoteXhFIiwiYXV0aCI6ImNtbDJiMkZzT201WU9ITXphWGxrTkhwdU5YZHpVbm90ZVhoRiJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: koublis
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-db
  namespace: koublis
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: koublis-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-db
  namespace: koublis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: data-db
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: koublis-db
  namespace: koublis
  labels:
    app: koublis-db
spec:
  replicas: 1
  serviceName: koub-db
  selector:
    matchLabels:
      app: koublis-db
  template:
    metadata:
      labels:
        app: koublis-db
    spec:
      initContainers:
        - name: init-data-db
          image: busybox
          command: ['sh', '-c', "while [ ! -d /var/lib/mysql/lost+found ]; do sleep 1; done"]
          volumeMounts:
            - mountPath: /data/db
              name: data-db
      containers:
        - name: koublis-db
          image: mongo:4.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: data-db
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
            limits:
              cpu: 200m
              memory: 500Mi
      volumes:
        - name: data-db
          persistentVolumeClaim:
            claimName: data-db
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: koublis
  labels:
    app: koublis-db
spec:
  ports:
    - port: 27017
  selector:
    app: koublis-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: koublis
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: db-svc.koublis.svc.cluster.local
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: connarde
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
  namespace: koublis
  labels:
    app: mongo-express
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: mongo-express
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mongo-express-ingress
  namespace: koublis
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: midd-auth@file
spec:
  rules:
    - host: mongodb.celld.tk
      http:
        paths:
          - path: /
            backend:
              serviceName: mongo-express-svc
              servicePort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: koublis
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry.celld.tk/koublis/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: db-svc.koublis.svc.cluster.local
#            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
#              value: root
#            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
#              value: connarde
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 300Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: koublis
  labels:
    app: api
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: api
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: koublis
spec:
  rules:
    - host: koublis.celld.tk
      http:
        paths:
          - path: /
            backend:
              serviceName: api-svc
              servicePort: 80
