### Sign-up as a new user
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword",
  "email": "testemail",
  "role": "ROLE_USER"
}

###

### Sign-up as a new user
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

###