spring:
  datasource:
    url: # Set automatically by the test container
    username: # Set automatically by the test container
    password: # Set automatically by the test container
    driver-class-name: # Set automatically by the test container
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0

koublis:
  catalog:
    location: catalog/catalog-test.json
  security:
    jwtSecret: j6F326G7UuS7wmIJ3Pca9vwV/s0QoIXImMsZMVG96cY=
    jwtExpiration: 1h

logging:
  level:
    com.koublis: debug